version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
    versioning-strategy: "increase-if-necessary"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "psr/container"
    groups:
      production-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
    assignees:
      - "blast007"
